---
driver:
  name: vagrant

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  run_list:
  - recipe[apt]
- name: centos-6.5

suites:
- name: system_ruby
  run_list:
  - recipe[ruby_build]
  - recipe[rbenv::system]
  attributes:
    rbenv:
      plugins:
      - name: rbenv-vars
        git_url: https://github.com/sstephenson/rbenv-vars.git
      rubies:
      - name: 1.9.3-p429
        environment:
          CONFIGURE_OPTS: --disable-install-rdoc
      - name: ree-1.8.7-2012.02
        environment:
          CONFIGURE_OPTS: --no-tcmalloc --no-dev-docs
      global: 1.9.3-p429
